POST https://rollingvet.herokuapp.com/api/signin
content-type: application/json

{
    "email": "ezea2002@hotmail.com",
    "password": "123456aA"
}

###

GET https://rollingvet.herokuapp.com/api/auth


###
GET http://localhost:5000/api/citasProgramadas/43706393